CREATE TABLE newsletter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    data_inscricao TIMESTAMP NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    token_unsubscribe UUID NOT NULL
);

-- Índice para busca rápida e segura durante o processo de unsubscribe
CREATE INDEX idx_newsletter_token ON newsletter(token_unsubscribe);
